language: python

python:
  - "3.6"

service:
  - postgresql

before_install:
  - export FLASK_APP=run.py
  - export FLASK_CONFIG="testing"
  
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage

before_script:
  - psql -c 'create database recipestest;' -U postgres
  - flask db init
  - flask db migrate
  - flask db upgrade

script:
  - nosetests --with-coverage --cover-erase --cover-package=app

after_success:
  - coveralls
